name: vox_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_dotenv: ^5.2.1
  flutter_tts: ^4.2.3
  go_router: ^15.1.2
  http: ^1.4.0
  permission_handler: ^12.0.0+1
  sensors_plus: ^6.1.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
